version: '3.8'

services:
  file-compressor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-compressor
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-compressor.rule=Host(`filecompressor.konnektline.com`)"
      - "traefik.http.routers.file-compressor.tls=true"
      - "traefik.http.routers.file-compressor.tls.certresolver=letsencrypt"
      - "traefik.http.services.file-compressor.loadbalancer.server.port=80"
    networks:
      - file-compressor-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a monitoring service
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
    networks:
      - file-compressor-network

networks:
  file-compressor-network:
    driver: bridge